# Generated by Django 5.1.1 on 2024-09-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categoty',
            new_name='category',
        ),
    ]
